_wandb:
    value:
        cli_version: 0.25.0
        code_path: source-Fin-estimator-_home_batto_AdvisorBot_reinforcement-learning_7_Reinforcement_learning.ipynb
        e:
            78ypcwoa0tjxprjb8duizh3rv9udzfp3:
                codePath: /home/batto/AdvisorBot/reinforcement-learning/7_Reinforcement_learning.ipynb
                codePathLocal: 7_Reinforcement_learning.ipynb
                cpu_count: 20
                cpu_count_logical: 20
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "162218242048"
                email: toogii@gmail.com
                executable: /home/batto/pythonenvs/advisorbot-rl-3.14/bin/python
                git:
                    commit: a0f31dabe89b8201039ccad37656ed9d3e40c296
                    remote: git@github.com:itoogii/AdvisorBot.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-4b4f1acd-ef02-c7ab-f664-895403d8c8fb
                host: Force
                memory:
                    total: "25198489600"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/batto/AdvisorBot/reinforcement-learning/7_Reinforcement_learning.ipynb
                python: CPython 3.14.2
                root: /home/batto/AdvisorBot/reinforcement-learning
                startedAt: "2026-03-04T04:59:26.422794Z"
                writerId: 78ypcwoa0tjxprjb8duizh3rv9udzfp3
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 35
            "4": 3.14.2
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
discount_factor:
    value: 0.99
epsilon:
    value: 1
epsilon_decay:
    value: 3e-07
learning_rate:
    value: 0.0001
