research_investor_task:
  description: >
    Conduct a thorough research about retail investors in US and UK users.
    Identify and find diverse retail investor information covering a wide range of financial literacy levels, investment goals, and tech comfort levels. Make sure you find demographics, investment behaviors, risk tolerances, emotional triggers, and common pain points encountered of retail investors in the stock market. Ensure the research captures the needs and preferences of age generations in GenZ, Millennials, GenX, and Boomers. Your research findings will be used by persona expert to create realistic and well-defined user personas for the financial advisor application users.
  expected_output: >
    Well structured, comprehensive user research detailing retail investors with demographics, their characteristics, behaviors, concerns and interests. Formatted as markdown without '```'
  agent: user_researcher

persona_creation_task:
  description: >
    Use the user research you got and create individual user personas. Make sure the personas have  Name, age, gender, location (in UK or USA), marital status, childrens (yes/no), occupation
    Qualities summarizing their character (Avoid getting too witty, as doing so may taint the persona as being too fun and not a useful tool. Example: friendly, humorous)
    Experience level with investment in stock market, their financial health, their risk tolerance in investing, their prior experience in stock market investment,
    Quotes to sum up the persona's attitude, Lifestyle (work, hobbies), speech style, optionally memory influenced by long and short term personal financial experiences and contains any and all relevant information. Include specific details to make the character more realistic, believable, and memorable. Each piece of information should have a purpose for being included in the persona, and should contribute creating realistic conversation scenarios later.
    Make sure the result is complete and contains all relevant information. Create 100 different users personas. 
  agent: persona_creator
  context: 
    - research_investor_task
  expected_output: PersonaList
  output_file: personas.json


