research_investor_task:
  description: >
    Conduct a thorough retail investor research for the financial advisor chatbot application. User research focuses in US and UK retail investors.
    Identify and define diverse retail investor profiles covering a wide range of financial literacy levels, investment goals, and tech comfort levels. Gather insights on demographics, investment behaviors, risk tolerances, emotional triggers, and common pain points faced by retail investors in the stock market. Ensure the research captures the needs and preferences of various age groups including GenZ, Millennials, GenX, and Boomers. The research findings will be used to create realistic and well-defined user personas for the chatbot application.
  expected_output: >
    Comprehensive user research report detailing retail investor demographics, their characteristics, behaviors, concerns and needs.
  agent: user_researcher

persona_task:
  description: >
    Review and identify the characteristics of the user information from the user research. 
    Begin the persona-creation process by identifying characteristics of users observed from user research. As you group these attributes into clusters, they will begin forming clear characters. If several seem too similar, merge them together or eliminate any groups that appear less relevant to the product or business. Once distinct roles emerge, add specific details to make the character more realistic, believable, and memorable. Each piece of information should have a purpose for being included and if it would not relate the persona, remove it.
    Make sure the result is complete and contains all relevant information. Generate user personas for at least 100 users based on the user research result, but do not exceed 500 users. Stop immediately after generating user personas for 500 users.
  expected_output: >
    JSON formatted list of user personas with:
    -	Name
    - age 
    - gender
    - location (in UK or USA)
    - marital status
    - children (yes/no)
    - occupation
    -	Speech style
    - Description (Qualities summarizing their character and persona's attitude. Avoid getting too witty, as doing so may taint the persona as being too fun and not a useful tool. Experience level in the stock market investment. Goals and concerns. Lifestyle. The preference of the investment as such value stock, regular dividend, or growth stock. Optionally add memory that influenced by the user's long and short term personal financial experiences)
    -	Image prompt that describes the user persona for AI image generation 
  agent: persona_creator
  output_file: personas.json


scenario_task:
  description: >
    Using the developed user personas, design engaging conversation scenarios for the AI-powered financial advisor chatbot application. Each scenario should reflect realistic user interactions based on the characteristics and needs of the personas, covering stock investment topics and financial dialogue in stock investment. Ensure that the scenarios include diverse situations such as market fluctuations, investment goal setting, and risk tolerance discussions to prepare the chatbot for a wide range of user inquiries. The chatbot responses must be informative, empathetic, and tailored to user needs, guiding users through investment decisions, risk assessments, and portfolio management while ensuring compliance with financial regulations based on user locations in the US or UK.
  expected_output: >
    A collection of detailed conversation scenarios in JSON format, each linked to specific user personas. Each scenario should include:
    - Persona reference
    - Scenario context
    - User goals and concerns
    - Sample dialogue exchanges
    - Key points for chatbot responses
  agent: scenario_planner
  output_file: conversation_scenarios.json

